# Generated by Django 4.2.1 on 2023-05-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_game_drawn_player_game_played_player_game_won_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game_drawn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='game_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='game_won',
            field=models.IntegerField(default=0),
        ),
    ]
