# Generated by Django 4.2.1 on 2023-05-06 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_alter_player_game_drawn_alter_player_game_played_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameWithBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgn', models.CharField(default='', max_length=500)),
                ('played_as', models.CharField(choices=[('bagh', 'BAGH'), ('goat', 'GOAT')], max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
