# Generated by Django 4.2.1 on 2023-05-07 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0005_alter_gamewithbot_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multiplayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgn', models.CharField(default='', max_length=500)),
                ('player1_played_as', models.CharField(choices=[('bagh', 'BAGH'), ('goat', 'GOAT')], max_length=6)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_game', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_game', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
