# Generated by Django 4.2.1 on 2023-05-10 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0012_alter_room_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='active',
        ),
        migrations.CreateModel(
            name='Mapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(default='', max_length=500, unique=True)),
                ('player1', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1_mapper', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2_mappers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
