# Generated by Django 4.2.1 on 2023-05-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_remove_room_active_mapper'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.CharField(default='', max_length=500),
        ),
    ]
